# Generated by Django 5.1 on 2024-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_automated',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
