# Generated by Django 5.1 on 2024-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_automated_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_automated',
            old_name='hours',
            new_name='hours_not_updated',
        ),
        migrations.AddField(
            model_name='event_automated',
            name='hours_updated',
            field=models.FloatField(default=0.0),
        ),
    ]
