# Generated by Django 5.1 on 2024-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_hours_event_automated_hours_not_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_automated',
            name='people_attended',
            field=models.IntegerField(default=0),
        ),
    ]
