# Generated by Django 5.1 on 2024-08-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_automated_people_attended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Automated',
        ),
    ]
