# Generated by Django 5.1 on 2024-08-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Automated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_title', models.CharField(default='no name', max_length=255)),
                ('hours_updated', models.FloatField(default=0.0)),
                ('hours_not_updated', models.FloatField(default=0.0)),
                ('people_attended', models.IntegerField(default=0)),
            ],
        ),
    ]
