# Generated by Django 5.1.1 on 2024-09-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyclub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_automated',
            old_name='hours_updated',
            new_name='hours_logged',
        ),
        migrations.RenameField(
            model_name='event_automated',
            old_name='hours_not_updated',
            new_name='hours_not_logged',
        ),
    ]
