# Generated by Django 5.1.1 on 2024-09-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyclub', '0002_rename_hours_updated_event_automated_hours_logged_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Automated',
            new_name='Event_Logged',
        ),
    ]
